services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  ForumBundle\Controller\:
    resource: '../../Controller/'
  ForumBundle\Repository\:
    resource: '../../Repository/'
  ForumBundle\Service\:
    resource: '../../Service/'
    public: true
  ForumBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  ForumBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  ForumBundle\Command\:
    resource: '../../Command/'
  ForumBundle\EntityListener\:
    resource: '../../EntityListener/'
